### ISSUE TITLE
Unrecognized logcat format error propagates to uncaught exception handler

### ISSUE THREAD

**Issue by mlopatkin** [mlopatkin/andlogview#329]
```
2023-11-19 19:26:32,990 [AWT-EventQueue-0] ERROR file.FileOpener - Unrecognized file format for D:\Temp\bugreport-sdk_gphone64_x86_64-UE1A.230829.036-2023-11-19-18-24-45.txt
name.mlopatkin.andlogview.liblogcat.file.UnrecognizedFormatException: Cannot load dumpstate file, no valid logcat section found
	at name.mlopatkin.andlogview.liblogcat.file.DumpstateFileDataSource$Builder.readFrom(DumpstateFileDataSource.java:183)
	at name.mlopatkin.andlogview.liblogcat.file.FileDataSourceFactory.createDumpstateFileSource(FileDataSourceFactory.java:85)
	at name.mlopatkin.andlogview.liblogcat.file.FileDataSourceFactory.createDataSource(FileDataSourceFactory.java:60)
	at name.mlopatkin.andlogview.liblogcat.file.FileDataSourceFactory.createDataSource(FileDataSourceFactory.java:43)
	at name.mlopatkin.andlogview.ui.file.FileOpener.openFileAsDataSource(FileOpener.java:93)
	at java.util.Optional.map(Optional.java:215)
	at name.mlopatkin.andlogview.ui.file.FileOpener.selectAndOpenFile(FileOpener.java:87)
	at name.mlopatkin.andlogview.MainFrame.startOpeningDataSource(MainFrame.java:478)
	at name.mlopatkin.andlogview.MainFrame.startOpeningDataSource(MainFrame.java:469)
	at name.mlopatkin.andlogview.MainFrame.selectAndOpenFile(MainFrame.java:448)
	at name.mlopatkin.andlogview.widgets.ActionBuilder$1.actionPerformed(ActionBuilder.java:36)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2023-11-19 19:26:34,733 [AWT-EventQueue-0] ERROR andlogview.Main - Uncaught exception in AWT-EventQueue-0
name.mlopatkin.andlogview.liblogcat.file.UnrecognizedFormatException: Cannot load dumpstate file, no valid logcat section found
	at name.mlopatkin.andlogview.liblogcat.file.DumpstateFileDataSource$Builder.readFrom(DumpstateFileDataSource.java:183)
	at name.mlopatkin.andlogview.liblogcat.file.FileDataSourceFactory.createDumpstateFileSource(FileDataSourceFactory.java:85)
	at name.mlopatkin.andlogview.liblogcat.file.FileDataSourceFactory.createDataSource(FileDataSourceFactory.java:60)
	at name.mlopatkin.andlogview.liblogcat.file.FileDataSourceFactory.createDataSource(FileDataSourceFactory.java:43)
	at name.mlopatkin.andlogview.ui.file.FileOpener.openFileAsDataSource(FileOpener.java:93)
	at java.util.Optional.map(Optional.java:215)
	at name.mlopatkin.andlogview.ui.file.FileOpener.selectAndOpenFile(FileOpener.java:87)
	at name.mlopatkin.andlogview.MainFrame.startOpeningDataSource(MainFrame.java:478)
	at name.mlopatkin.andlogview.MainFrame.startOpeningDataSource(MainFrame.java:469)
	at name.mlopatkin.andlogview.MainFrame.selectAndOpenFile(MainFrame.java:448)
	at name.mlopatkin.andlogview.widgets.ActionBuilder$1.actionPerformed(ActionBuilder.java:36)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2023-11-19 19:26:35,926 [AWT-EventQueue-0] ERROR andlogview.Main - Uncaught exception in AWT-EventQueue-0
java.util.concurrent.CompletionException: name.mlopatkin.andlogview.liblogcat.file.UnrecognizedFormatException: Cannot load dumpstate file, no valid logcat section found
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:838)
	at java.util.concurrent.CompletableFuture.uniHandleStage(CompletableFuture.java:848)
	at java.util.concurrent.CompletableFuture.handle(CompletableFuture.java:2168)
	at name.mlopatkin.andlogview.MainFrame.startOpeningDataSource(MainFrame.java:484)
	at name.mlopatkin.andlogview.MainFrame.startOpeningDataSource(MainFrame.java:469)
	at name.mlopatkin.andlogview.MainFrame.selectAndOpenFile(MainFrame.java:448)
	at name.mlopatkin.andlogview.widgets.ActionBuilder$1.actionPerformed(ActionBuilder.java:36)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.AbstractButton.doClick(AbstractButton.java:376)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:842)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:886)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: name.mlopatkin.andlogview.liblogcat.file.UnrecognizedFormatException: Cannot load dumpstate file, no valid logcat section found
	at name.mlopatkin.andlogview.liblogcat.file.DumpstateFileDataSource$Builder.readFrom(DumpstateFileDataSource.java:183)
	at name.mlopatkin.andlogview.liblogcat.file.FileDataSourceFactory.createDumpstateFileSource(FileDataSourceFactory.java:85)
	at name.mlopatkin.andlogview.liblogcat.file.FileDataSourceFactory.createDataSource(FileDataSourceFactory.java:60)
	at name.mlopatkin.andlogview.liblogcat.file.FileDataSourceFactory.createDataSource(FileDataSourceFactory.java:43)
	at name.mlopatkin.andlogview.ui.file.FileOpener.openFileAsDataSource(FileOpener.java:93)
Caused by: name.mlopatkin.andlogview.liblogcat.file.UnrecognizedFormatException: Cannot load dumpstate file, no valid logcat section found

	at java.util.Optional.map(Optional.java:215)
	at name.mlopatkin.andlogview.ui.file.FileOpener.selectAndOpenFile(FileOpener.java:87)
	at name.mlopatkin.andlogview.MainFrame.startOpeningDataSource(MainFrame.java:478)
	... 41 more
```

**Comment by mlopatkin** [comment]
Fixed in b05169d5aff8895cdb7204e757d98a0f362d7a36
