### ISSUE TITLE
Strange exception when opening a file with drag'n'drop

### ISSUE THREAD

**Issue by mlopatkin** [mlopatkin/andlogview#94]
**[Original report](https://bitbucket.org/mlopatkin/android-log-viewer/issue/94) by me.**

----------------------------------------

Strange Exception (once)
# Open the tool in adb mode with device connected
# Drag and drop some log file to it.

```
2012-04-05 19:55:04,072 [main] INFO  org.bitbucket.mlopatkin.android.logviewer.Main - Android Log Viewer 0.17.4
2012-04-05 19:55:06,776 [ADB-polling-RADIO] ERROR org.bitbucket.mlopatkin.android.liblogcat.LogRecordStream - Unexpected IO exception
java.io.IOException: Pipe closed
	at java.io.PipedInputStream.read(Unknown Source)
	at java.io.PipedInputStream.read(Unknown Source)
	at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
	at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
	at sun.nio.cs.StreamDecoder.read(Unknown Source)
	at java.io.InputStreamReader.read(Unknown Source)
	at java.io.BufferedReader.fill(Unknown Source)
	at java.io.BufferedReader.readLine(Unknown Source)
	at java.io.BufferedReader.readLine(Unknown Source)
	at org.bitbucket.mlopatkin.android.liblogcat.LogRecordStream.next(LogRecordStream.java:53)
	at org.bitbucket.mlopatkin.android.liblogcat.ddmlib.AdbBuffer$PollingThread.run(AdbBuffer.java:71)
2012-04-05 19:55:06,791 [AWT-EventQueue-0] ERROR org.bitbucket.mlopatkin.android.logviewer.Main - Uncaught exception in AWT-EventQueue-0
java.lang.NullPointerException
	at javax.swing.JComponent.scrollRectToVisible(Unknown Source)
	at org.bitbucket.mlopatkin.android.logviewer.ListScrollController.performScrollToTheEnd(ListScrollController.java:56)
	at org.bitbucket.mlopatkin.android.logviewer.AutoScrollController$1.run(AutoScrollController.java:67)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$000(Unknown Source)
	at java.awt.EventQueue$1.run(Unknown Source)
	at java.awt.EventQueue$1.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)

```

**Comment by mlopatkin** [comment]
It's been a while since I saw this one. Please file a new issue or comment here if the problem keeps happening.
